cloud/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('drive.urls', namespace='files')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drive/urls.py
from django.urls import path
from .models import Drive
from .views import login_request, homepage, logout_request
from .views import my_files

app_name = 'drive'

urlpatterns = [
    path('my-files/', my_files, name='my-files'),
    path("login/", login_request, name="login"),
    path("", homepage, name="homepage"),
    path('logout/', logout_request, name='logout')
]

drive/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


class Profile(User):

    def __str__(self):
        return self.username


class Drive(models.Model):
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='uploads/', max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')
    permissions = models.ForeignKey(Profile, on_delete=CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        return self.title

drive/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.core.checks import messages
from django.shortcuts import render, redirect
from .models import Drive
from django.contrib.auth import REDIRECT_FIELD_NAME, authenticate, login, logout
from django.contrib.auth.decorators import login_required
import os


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("files:homepage")
    form = AuthenticationForm()
    context = {"login_form": form}
    return render(request, "login.html", context)


@login_required(login_url='files:login')
def my_files(request):
    drive = Drive.objects.filter(owner_id=request.user.id)
    files = []
    dl = []
    for file in drive:
        file_size = os.path.getsize(file.file.path)
        file_size = file_size/1000
        dl.append(file.file.url)
        files.append(file_size)

    ctx = {'files': dl,
           'size': sum(files)}
    return render(request, 'index.html', ctx)


def homepage(request):
    ctx = {'username': request.user.username}
    return render(request, 'home.html', ctx)


def logout_request(request):
    logout(request)
    return redirect('files:homepage')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    {% block content %}

    {% endblock content %}

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% if user.is_authenticated %}
        <p> hello {{ user.username }}</p>
        <div>
            <ul>
                <li>
                    <a href="{% url 'files:my-files' %}"> files </a>
                </li>
                <li>
                    <a href="/admin/">admin</a>
                </li>
                <li>
                    <a href="{% url 'files:logout' %}"> logout </a>
                </li>

            </ul>
    </div>
    {% else %}

        <div>
            <ul>
                <li>
                    <a href="{% url 'files:my-files' %}"> files </a>
                </li>
                <li>
                    <a href="/admin/">admin</a>
                </li>
                <li>
                    <a href="{% url 'files:login' %}"> login </a>
                </li>

            </ul>
        </div>
    {% endif %}
    {% block content %}

    {% endblock content %}

templates/index.html
{% block content %}
<div>
    <p>hello {{ user.username }}</p>

    <p> total file size: {{ size }} kbs</p>

    {% for file in files %}
        <p><a href={{ file }}>{{ file.title }}/{{ file.file }}</a></p>
    {% endfor %}
</div>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block title %} login {% endblock title %}


{% block content %}
 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
</div>

{% endblock %}